# Generated by Django 2.2.6 on 2019-10-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('match', models.CharField(max_length=20)),
                ('kill', models.PositiveIntegerField(default=0)),
                ('time', models.TimeField(null=True)),
                ('score', models.PositiveIntegerField(editable=False, null=True)),
            ],
        ),
    ]
